# Generated by Django 3.0 on 2019-12-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name_author',
            new_name='author_name',
        ),
    ]
