# Generated by Django 3.0 on 2019-12-12 15:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191209_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_news',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
